; PlatformIO Project Configuration File
; Toren Monitoring System — Kelompok E-08 Capstone DTETI UGM 2026
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0

build_flags =
    -D CORE_DEBUG_LEVEL=0
